#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 2001
ENV ASPNETCORE_URLS=http://+:2001

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["ikeamind-backend.JwtAuth/ikeamind-backend.JwtAuth.csproj", "ikeamind-backend.JwtAuth/"]
COPY ["ikeamind-backend.Infrastructure/ikeamind-backend.Infrastructure.csproj", "ikeamind-backend.Infrastructure/"]
COPY ["ikeamind-backend.Core/ikeamind-backend.Core.csproj", "ikeamind-backend.Core/"]
RUN dotnet restore "ikeamind-backend.JwtAuth/ikeamind-backend.JwtAuth.csproj"
COPY . .
WORKDIR "/src/ikeamind-backend.JwtAuth"
RUN dotnet build "ikeamind-backend.JwtAuth.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ikeamind-backend.JwtAuth.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ikeamind-backend.JwtAuth.dll"]